### ISSUE TITLE
Documentation for specifying custom atlas or parcellation?

### ISSUE THREAD

**Issue by mnarayan** [BIDS-Apps/ndmg#13]
I assumed from ndmg documentation that structural connectomes can be created using many pre-defined atlases. However, the README doesn't mention how to specify location of an atlas as an input.

**Comment by gkiar** [comment]
Hi! We currently support 24 parcellations within the container, including
many of the popular ones distributed with tools like FSL, but the BIDs app
doesn't allow users to specify other parcellations - this is done so that
we can ensure the quality of the parcellations used, and users won't
accidentally use atlases that are not aligned to the MNI152 space.

If you want to send me your atlas I can test it, ensure it aligns, and
integrate it into the pipeline.

Alternatively, if you bypass the entrypoint in this container and run the
pipeline directly, without the BIDS directory crawling, I can help you use
your own parcellation. This solution is much uglier and more annoying to
parallellize, so I suggest the former.

Let me know how you'd like to proceed!
Greg

--
Greg Kiar <gkiar07@gmail.com>

**Comment by mnarayan** [comment]
Hi Greg,
Does ndmg produce outputs for all 24 parcellations by default? I just assumed there would be an option to choose some subset of them (and/or specify a custom one) but the predefined ones should suffice for me. 

Thanks,
Manjari

**Comment by gkiar** [comment]
Yup - all connectomes will be generated automatically :) They range from ~48 to ~72,000 nodes. Please close the issue if you're happy, and let me know if you have more questions!

**Comment by chrisgorgo** [comment]
As a shameless plug I just mention that you can run ndmg in the cloud for free on your data using http://OpenNeuro.org. Here's ana example output with all 24 parcellations: https://openneuro.org/datasets/ds000108/versions/3030303130382d3030303031?app=ndmg&version=14
