### ISSUE TITLE
Poor Skull-Strip?

### ISSUE THREAD

**Issue by jlhanson5** [BIDS-Apps/ndmg#16]
Hello ndmg users,

I had an issue as I started to test-drive the ndmg BIDS app. I hadn't dug into the outputs extensively, but I noticed that skull-stripping of the t1-weighted image was generally quite poor (see example below; yellow is the skull-stripped mask overlayed on an anatomical). I wondered if others had run into this issue and if there were ways to improve this?

Thanks much,
Jamie.

<img width="608" alt="nmdg" src="https://user-images.githubusercontent.com/7240261/33076060-96e3b7d6-ce99-11e7-98ec-0aa64b013411.png">

**Comment by gkiar** [comment]
Hi @jlhanson5 - thanks for the note!

When we do skull stripping in ndmg, it's simply as an intermediate step to help the alignment from the subject-T1 to the MNI152 template. We chose an intentionally over-aggressive skull stripping parameter selection so that on no (tested) datasets would there be skull left that would disturb this alignment. Once the brain is aligned to MNI152 space, this brain mask is not used, but rather the MNI152 manually segmented mask.

So I suppose that is all to say, I have found `bet` to be somewhat inconsistent across variable quality data, so picked a setting that would robustly enable alignment to MNI152 and use only the "ground-truth" brain mask in that space. I'd recommend, if you're working on the aligned volumes, using that mask as well.

Does that help?

Cheers,
Greg

**Comment by jlhanson5** [comment]
Ah my mistake! That's good to know (and your explanation makes sense). 

Somewhat related, does your group have an guidance about doing QC on the ndmg processing? I know there's some pngs output during processing. Is it best to just inspect them? Other suggestions?

**Comment by gkiar** [comment]
Hi @jlhanson5 - sorry for the delay in getting back to you.

I'd suggest running group analysis on the output connectomes, and then you'll receive an interactive HTML plot of graph summary statistics which can serve as a good quality control reference and springboard exploratory analysis on your data.

Of note: the summary statistic computation can accept an `--atlas` argument which will tell it which parcellation to do this analysis for. The larger parcellations (i.e. more nodes) will take a very long time and may fail (if there are isolates in the graphs, i.e. unconnected regions), so we recommend sticking to smaller parcellations such as the Desikan, CPAC200, JHU, AAL, HarvardOxford, etc... 

There was a discussion somewhere about this crash-condition several months ago that I'm trying to find and will link if I succeed. The short version is that it is non-trivial to simply use the largest connected component (LCC) graphs as each graph may have different isolates or different numbers of isolates, resulting in mis-aligned LCCs, so we couldn't directly compare node A in one to node A in another.
