### ISSUE TITLE
Update Dockerfile to ensure smooth operation of singularity container

### ISSUE THREAD

**Issue by mnarayan** [BIDS-Apps/ndmg#18]
Hi

I tried to use the Dockerfile to automatically build a singularity container. 
Fork with singularity configuration: https://github.com/TheEtkinLab/ndmg
Singularity container: https://www.singularity-hub.org/collections/480

Here is how I pull and check installation
```
singularity pull singularity pull shub://TheEtkinLab/ndmg:v0.0.50
singularity shell TheEtkinLab-ndmg-master.simg
Singularity: Invoking an interactive shell within container...
Singularity TheEtkinLab-ndmg-master.simg:/home/groups/<name>/singularity_images> which ndmg_bids
/usr/local/bin/ndmg_bids
```
However I run into permission errors when I run the container or try to run `ndmg_bids`
```
Singularity TheEtkinLab-ndmg-master.simg:/home/groups/<name>/singularity_images> ndmg_bids -h
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/.wh.plotly-1.12.9.egg-info'
```
Not sure if this is a singularity build issue or what. But I don't have this issue with C-PAC singularity builds, so I'm guessing they have a better Dockerfile configuration/installation. 
repo: https://github.com/TheEtkinLab/CPAC
singularity container: https://www.singularity-hub.org/collections/196 

Any help appreciated. 
Thanks,

**Comment by chrisgorgo** [comment]
This is a know (but potentially recently resolved) Singularity issue. See https://github.com/singularityware/singularity/issues/884

**Comment by mnarayan** [comment]
Thanks @chrisfilo. So it sounds like the version of singularity that was used to build this container was flawed and container needs to be re-built using a newer version?

**Comment by chrisgorgo** [comment]
Could be. It might be worth trying to use docker2singularity to perform the
conversion: https://github.com/singularityware/docker2singularity

Best,
Chris

**Comment by gkiar** [comment]
@chrisfilo, would it be worth adding a `docker2singularity` run to the circle.yml script, and push the image to singularity hub with the same versioning once tests pass?

**Comment by chrisgorgo** [comment]
AFAIK Singularity Hub does not allow users to push images. Only autobuild is possible. Perhaps things have changed @vsoch

**Comment by vsoch** [comment]
Singularity Hub can't be pushed to directly, but we have a deployment option that will (on success of your circle tests) build the image from the connected repo on Singularity Hub. You would either have a Singularity file with the same content (annoying and redundant) or just one that has the minimum guts to specify the image (the header), e.g.:

```
Bootstrap:docker
From: BIDS-Apps/dmg
```

To do this, you would want to connect the repo, click on Build Settings, and then select "deployment" as the build trigger.

We don't (yet) have a direct push because credentials are managed using Github as a middleman, and having a direct push would mean giving users credentials that they put on servers like travis and what not.

Another option If you want to push images to some flavor of storage is to use the Singularity Registry Global Client, which can interact with traditional docker, nvidia cloud, a hosted Singularity Registry, but also places like Google Cloud Storage / Drive, Nvidia Cloud, a Singularity Registry (to which you could push directly given being an administrator) and in the works, Dropbox.

The client (and linked example is for the Singularity Registry storage endpoint) is here:

https://singularityhub.github.io/sregistry-cli/client-registry

The above is a local database to manage your images that will generally pull, push, inspect between all these storage endpoints. If you want to a host a registry for your group or institution (a more substantial database and web interface) then you would want a Singularity Registry proper:

https://singularityhub.github.io/sregistry/

And you would easily be able to push to that with a token, and others can pull with Singularity native software and/or the global client. 

Singularity Hub proper is expected to be expanded to allow for push for the next big release, but I won't have time to do this soon. But in the mean time, to better support your groups, are there other cloudy / storage places you would like the Singularity Registry client to push? I can add them to the list! Definitely check out the Google Drive share, it's very cool!! You can run a "share" command and send someone a link to download your image on Drive. If BIDS has APIs/ tools that would warrant an integration, we could  make one too.

**Comment by vsoch** [comment]
And since I'm fantastic of probably not answering your question, here are the different build options we offer (for Singularity Hub):

https://github.com/singularityhub/singularityhub.github.io/wiki#meet-the-builders

**Comment by gkiar** [comment]
@vsoch this is super helpful, thanks! I'll investigate the first option you mentioned, and failing that will definitely check out the Google Drive option, which sounds awesome. 😄

**Comment by vsoch** [comment]
Awesome! Please post an issue if there are any bugs or you think of a cool feature. Glad to help :)

**Comment by mnarayan** [comment]
@gkiar If you are able to provide a singularity container! I am unable to build singularity containers myself at the moment, so if the singularity version has a problem at https://www.singularity-hub.org/collections/480, I have to wait for the builders to be updated.

**Comment by vsoch** [comment]
@mnarayan I'm looking at your original issue - this is the infamous whiteout file bug! I believe we had a fix merged into development branch of singularity, could you try using that version? Unfortunately we can't update the shub builders until it's provided in an actual release, but if you build with the development it should be a way to continue making progress with your work.

**Comment by gkiar** [comment]
Hey @vsoch I've successfully built it on Singularity hub using your first suggestion, but find that using the Singularity 2.4.1-dist tool I'm unable to find the image name. I.e.:

```
$ singularity pull shub://BIDS-Apps/ndmg
ERROR Cannot find image. Is your capitalization correct?
```

Thanks!

**Comment by vsoch** [comment]
The reason is because you must ask specifically for the tag:

```
singularity pull shub://BIDS-Apps/ndmg:v0.1.0
```

If you don't provide one, it defaults to `latest` and that would coincide with having a bare `Singularity` file in your repository. So if you want latest to always sync up with a particular version, just make a symbolic link to it (I think Github allows that to work?) Anyway, just try the above!

**Comment by gkiar** [comment]
Ah of course! I copy pasted directly from [here](https://www.singularity-hub.org/collections/516/usage) and didn't think. Thanks :)

**Comment by vsoch** [comment]
haha yeah, bad documentation on my part :)

**Comment by gkiar** [comment]
Hah, I don't know about that :) Thanks for all your help here!

@mnarayan I believe we can close this now. Also, you can use my Singularity image directly (adapted from your script), at `BIDS-Apps/ndmg:v0.1.0`.

**Comment by mnarayan** [comment]
Thanks so much @gkiar

**Comment by mnarayan** [comment]
@gkiar I was able to successfully build singularity containers on shub but ran into the same white out issue that started this thread. I just tried out your container and it still has the same issue.  

```
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/.wh.plotly-1.12.9.egg-info'
```
Was this container built using the fix @vsoch suggested using above? 


>@mnarayan I'm looking at your original issue - this is the infamous whiteout file bug! I believe we had a fix merged into development branch of singularity, could you try using that version? Unfortunately we can't update the shub builders until it's provided in an actual release, but if you build with the development it should be a way to continue making progress with your work.

**Comment by vsoch** [comment]
On Singularity Hub I'm using the standard of updating the builders only with versioned releases, so the development fix isn't there. So you can build with development locally, or wait for the next release. The first is probably faster!

**Comment by gkiar** [comment]
@mnarayan I don't have the issue you're describing when running the commands as you've pasted them above. What version of the singularity runtime are you using?

**Comment by mnarayan** [comment]
It is singularity/2.4.

**Comment by vsoch** [comment]
That sounds like the module loaded from SCG4 or Sherlock, in which case the fix isn't there. I would:

 - install development branch on your local machine
 - pull the image
 - transfer to cluster

**Comment by mnarayan** [comment]
@vsoch Does this mean the problem lies in which version of singularity is used to pull the image? But it won't be an issue to use singularity/2.4 afterwards?

**Comment by vsoch** [comment]
The bug likely exists with singularity/2.4, and was fixed after that. The fix is in the development branch, and not yet an official release.

So if you build locally with development branch, you won't have this issue. The Singularity Hub builders will only be updated with official releases. The release cycle is not going to be quick and so my recommendation is what I suggested above. Build it locally after you install development, and transfer to the cluster.
